### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/vpc-endpoint#33]
Issue on page:        https://github.com/opentelekomcloud-docs/vpc-endpoint/blob/main/umn/source/faq/index.rst

Would you please add VPC-EP Connection Limits?

**Comment by lhajba** [comment]
Your request is invalid, there is no issue on Frequently Asked Questions (FAQ) page because it doesn't describe connection limits.

What you might be searching for is described under the following pages: 
https://docs.otc.t-systems.com/vpc-endpoint/umn/vpc_endpoint_services/vpc_endpoint_service_overview.html
https://docs.otc.t-systems.com/vpc-endpoint/umn/vpc_endpoints/vpc_endpoint_overview.html
